// <auto-generated />
using System;
using Catalina.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalina.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220831195521_reaction_gone_crab")]
    partial class reaction_gone_crab
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Catalina.Database.Models.Emoji", b =>
                {
                    b.Property<string>("NameOrID")
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("NameOrID");

                    b.ToTable("Emojis");
                });

            modelBuilder.Entity("Catalina.Database.Models.GuildProperty", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("StarboardChannelID")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("StarboardEmojiNameOrID")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StarboardThreshhold")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StarboardEmojiNameOrID");

                    b.ToTable("GuildProperties");
                });

            modelBuilder.Entity("Catalina.Database.Models.Response", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("GuildPropertyID")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Trigger")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("GuildPropertyID");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Catalina.Database.Models.Role", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("GuildPropertyID")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsAutomaticallyAdded")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsColourable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRenamabale")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("GuildPropertyID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Catalina.Database.Models.StarboardMessage", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ChannelID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("GuildPropertyID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MessageID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("StarboardMessageID")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("ID");

                    b.HasIndex("GuildPropertyID");

                    b.ToTable("StarboardMessages");
                });

            modelBuilder.Entity("Catalina.Database.Models.StarboardVote", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("StarboardMessageID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("ID");

                    b.HasIndex("StarboardMessageID");

                    b.ToTable("StarboardVotes");
                });

            modelBuilder.Entity("Catalina.Database.Models.GuildProperty", b =>
                {
                    b.HasOne("Catalina.Database.Models.Emoji", "StarboardEmoji")
                        .WithMany()
                        .HasForeignKey("StarboardEmojiNameOrID");

                    b.Navigation("StarboardEmoji");
                });

            modelBuilder.Entity("Catalina.Database.Models.Response", b =>
                {
                    b.HasOne("Catalina.Database.Models.GuildProperty", null)
                        .WithMany("Responses")
                        .HasForeignKey("GuildPropertyID");
                });

            modelBuilder.Entity("Catalina.Database.Models.Role", b =>
                {
                    b.HasOne("Catalina.Database.Models.GuildProperty", null)
                        .WithMany("Roles")
                        .HasForeignKey("GuildPropertyID");
                });

            modelBuilder.Entity("Catalina.Database.Models.StarboardMessage", b =>
                {
                    b.HasOne("Catalina.Database.Models.GuildProperty", null)
                        .WithMany("StarboardMessages")
                        .HasForeignKey("GuildPropertyID");
                });

            modelBuilder.Entity("Catalina.Database.Models.StarboardVote", b =>
                {
                    b.HasOne("Catalina.Database.Models.StarboardMessage", null)
                        .WithMany("UserVotes")
                        .HasForeignKey("StarboardMessageID");
                });

            modelBuilder.Entity("Catalina.Database.Models.GuildProperty", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Roles");

                    b.Navigation("StarboardMessages");
                });

            modelBuilder.Entity("Catalina.Database.Models.StarboardMessage", b =>
                {
                    b.Navigation("UserVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
