// <auto-generated />
using System;
using Catalina.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalina.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220830140735_rewrite-emoji")]
    partial class rewriteemoji
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Catalina.Database.Models.Emoji", b =>
                {
                    b.Property<string>("NameOrID")
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("NameOrID");

                    b.ToTable("Emojis");
                });

            modelBuilder.Entity("Catalina.Database.Models.GuildProperty", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("StarBoardChannel")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("StarboardEmojiNameOrID")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StarboardThreshhold")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StarboardEmojiNameOrID");

                    b.ToTable("GuildProperties");
                });

            modelBuilder.Entity("Catalina.Database.Models.Reaction", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ChannelID")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("EmojiNameOrID")
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("GuildID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MessageID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("RoleID")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("ID");

                    b.HasIndex("EmojiNameOrID");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("Catalina.Database.Models.Response", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<string>("GuildID")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Trigger")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Catalina.Database.Models.Role", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("GuildPropertyID")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsAutomaticallyAdded")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsColourable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRenamabale")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("GuildPropertyID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Catalina.Database.Models.GuildProperty", b =>
                {
                    b.HasOne("Catalina.Database.Models.Emoji", "StarboardEmoji")
                        .WithMany()
                        .HasForeignKey("StarboardEmojiNameOrID");

                    b.Navigation("StarboardEmoji");
                });

            modelBuilder.Entity("Catalina.Database.Models.Reaction", b =>
                {
                    b.HasOne("Catalina.Database.Models.Emoji", "Emoji")
                        .WithMany()
                        .HasForeignKey("EmojiNameOrID");

                    b.Navigation("Emoji");
                });

            modelBuilder.Entity("Catalina.Database.Models.Role", b =>
                {
                    b.HasOne("Catalina.Database.Models.GuildProperty", null)
                        .WithMany("Roles")
                        .HasForeignKey("GuildPropertyID");
                });

            modelBuilder.Entity("Catalina.Database.Models.GuildProperty", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
