// <auto-generated />
using System;
using Catalina.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalina.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Catalina.Database.Models.Emoji", b =>
                {
                    b.Property<string>("NameOrID")
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("NameOrID");

                    b.ToTable("Emojis");
                });

            modelBuilder.Entity("Catalina.Database.Models.GuildProperty", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("StarboardID")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("ID");

                    b.HasIndex("StarboardID");

                    b.ToTable("GuildProperties");
                });

            modelBuilder.Entity("Catalina.Database.Models.Message", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ChannelID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MessageID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("StarboardID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("StarboardMessageID")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("ID");

                    b.HasIndex("StarboardID");

                    b.ToTable("StarboardMessages");
                });

            modelBuilder.Entity("Catalina.Database.Models.Response", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("GuildPropertyID")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Trigger")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("GuildPropertyID");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Catalina.Database.Models.Role", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("GuildPropertyID")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsAutomaticallyAdded")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsColourable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRenamabale")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("GuildPropertyID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Catalina.Database.Models.Starboard", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("ChannelID")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("EmojiNameOrID")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Threshhold")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EmojiNameOrID");

                    b.ToTable("Starboard");
                });

            modelBuilder.Entity("Catalina.Database.Models.Vote", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("MessageID")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("ID");

                    b.HasIndex("MessageID");

                    b.ToTable("StarboardVotes");
                });

            modelBuilder.Entity("Catalina.Database.Models.GuildProperty", b =>
                {
                    b.HasOne("Catalina.Database.Models.Starboard", "Starboard")
                        .WithMany()
                        .HasForeignKey("StarboardID");

                    b.Navigation("Starboard");
                });

            modelBuilder.Entity("Catalina.Database.Models.Message", b =>
                {
                    b.HasOne("Catalina.Database.Models.Starboard", null)
                        .WithMany("Messages")
                        .HasForeignKey("StarboardID");
                });

            modelBuilder.Entity("Catalina.Database.Models.Response", b =>
                {
                    b.HasOne("Catalina.Database.Models.GuildProperty", null)
                        .WithMany("Responses")
                        .HasForeignKey("GuildPropertyID");
                });

            modelBuilder.Entity("Catalina.Database.Models.Role", b =>
                {
                    b.HasOne("Catalina.Database.Models.GuildProperty", null)
                        .WithMany("Roles")
                        .HasForeignKey("GuildPropertyID");
                });

            modelBuilder.Entity("Catalina.Database.Models.Starboard", b =>
                {
                    b.HasOne("Catalina.Database.Models.Emoji", "Emoji")
                        .WithMany()
                        .HasForeignKey("EmojiNameOrID");

                    b.Navigation("Emoji");
                });

            modelBuilder.Entity("Catalina.Database.Models.Vote", b =>
                {
                    b.HasOne("Catalina.Database.Models.Message", null)
                        .WithMany("Votes")
                        .HasForeignKey("MessageID");
                });

            modelBuilder.Entity("Catalina.Database.Models.GuildProperty", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Catalina.Database.Models.Message", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Catalina.Database.Models.Starboard", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
